### ISSUE TITLE
Remove "Requires Java 8" from Jbang instructions?

### ISSUE THREAD

**Issue by quintesse** [jreleaser/jreleaser.github.io#27]
The line "Requires Java 8" is mentioned everywhere when mentioning Jbang but, although that's technically true, for the user that's practically speaking not an issue because Jbang will automatically download and install any necessary JDKs.

Can provide PR if you agree :-)

**Comment by aalmiray** [comment]
Right. JReleaser's JBang script already takes care of downloading a suitable JR if needed. That sentence can certainly be removed.

**Comment by aalmiray** [comment]
I think this issue has been solved
