### ISSUE TITLE
Document more about maven multi module project

### ISSUE THREAD

**Issue by ttddyy** [jreleaser/jreleaser.github.io#43]
In a multi module maven project, when JReleaser is configured on the parent pom, the child modules also run the release tasks.
I caught this behavior when the child module release task complained there is already the same version exists.
It may be ideal behavior in some cases, for example, when a project wants to perform release individually on each module, but I think in regular cases it wouldn't.

For my case, I just made the maven run `./mvnw jreleaser:full-release -pl .` to limit the maven root only.
Another way I could think of is to create a child module dedicated to performing the release rather than defining it in the parent pom.

In the JReleaser documentation, I find a mention of maven multi module project only [here](https://jreleaser.org/guide/latest/tools/jreleaser-maven.html).

> The value of project.java.multiProject will be set to true if the current Maven session has more than 1 project.

I think having more documentation about maven multi module project would help understand the behavior, and users could properly configure JReleaser.

**Comment by aalmiray** [comment]
Indeed. `jreleaser-maven-plugin` was not designed to be used multiple times in a multi-module Maven project. It's assumed that the plugin is applied at the root or at a given module that functions as the release driver. An example of a multi-module Maven setup should be added to the documentation for sure.

**Comment by aalmiray** [comment]
Also I think mojos may be implicitly configured to skip inheritance, that way JReleaser may configure itself the proper way without consumers having to specify `<inherited>false</inherited>` or run a sub-reactor as you did. Will look into it.
