### ISSUE TITLE
Broken links in search results

### ISSUE THREAD

**Issue by gunnarmorling** [jreleaser/jreleaser.github.io#51]
When searching e.g. for "token" in the "Search docs" input field on https://jreleaser.org/guide/, I'm getting "Page not found" errors.

**Comment by aalmiray** [comment]
Caused by a recent reorganization of pages. need to reset the search index.

Bad link -> https://jreleaser.org/guide/latest/configuration/packagers/homebrew.html#_tokens
Good link -> https://jreleaser.org/guide/latest/reference/packagers/homebrew.html#_tokens
